import "./globals.css";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //"md:text-[0.84dvw] text-[3.25dvw]"
  //md:text-[16px] text-[14px]
  return (
    <html
      lang="en"
      className="2xl:text-[16px] xl:text-[14px] md:text-[10px] text-[14px]"
    >
      <body>{children}</body>
    </html>
  );
}
