import "./globals.css";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="md:text-[0.84dvw] text-[3.25dvw]">
      <body>{children}</body>
    </html>
  );
}
